default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: quantified_self_rails_docker_development

test:
  <<: *default
  database: quantified_self_rails_docker_test

production:
  <<: *default
  database: quantified_self_rails_docker_production
